version: '3.8'

volumes:
  hospitaldb_vol:

networks:
  hc_micro:
    external:
      name: hc_micro

services:
  hospital-api:
    container_name: chospital-service
    build:
      context: .
    ports:
    - "5001:5001"
    depends_on:
      - hospital-db
    networks:
      - hc_micro
    restart: always

  surgery-db:
    container_name: chospital_dbase
    image: mysql:8
    ports:
    - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pfm_dc_2020
      MYSQL_DATABASE: hospital
      MYSQL_USER: cloudacademy
      MYSQL_PASSWORD: pfm_2020
    networks:
      - hc_micro
    volumes:
    - hospitaldb_vol:/var/lib/mysql